"""Jieli firmware conversion and artifact naming."""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
from pathlib import Path
from typing import Mapping

from .chip_profiles import JIELI_CHIPS
from .errors import BuildError
from .toolchain import resolve_tool_path


def generate_raw_app_bin(elf: Path, tools_dir: Path, tool_dir: Path, chip) -> Path:
    """Extract the application sections in the selected SDK's image order."""
    objcopy = resolve_tool_path(tool_dir, "objcopy")
    if not objcopy.is_file():
        raise BuildError(f"Jieli objcopy not found: {objcopy}")

    chunks: list[bytes] = []
    for section in chip.raw_app_sections:
        extracted = tools_dir / f".jieli{section.replace('.', '_')}.bin"
        result = subprocess.run(
            [str(objcopy), "-O", "binary", "-j", section, str(elf), str(extracted)],
            cwd=tools_dir,
            check=False,
        )
        if result.returncode != 0:
            raise BuildError(f"objcopy failed for ELF section {section}")
        if extracted.is_file():
            chunks.append(extracted.read_bytes())
            extracted.unlink()

    output = tools_dir / "app.bin"
    output.write_bytes(b"".join(chunks))
    if output.stat().st_size == 0:
        raise BuildError(f"Jieli ELF contains no application sections: {elf}")
    print(f"[JIELI] raw artifact: {output}")
    return output


def _run(command: list[str], cwd: Path, env: dict[str, str]) -> None:
    print(f"[JIELI] run: {shlex.join(command)}")
    result = subprocess.run(command, cwd=cwd, env=env, check=False)
    if result.returncode != 0:
        raise BuildError(f"command failed with exit code {result.returncode}: {command[0]}")


def run_postbuild(sdk_root: Path, tool_dir: Path, env: dict[str, str], chip) -> None:
    tools_dir = sdk_root / chip.sdk_source_relative / chip.tools_relative
    command_text = env.get("JIELI_POSTBUILD_CMD", "").strip()
    if command_text:
        _run(shlex.split(command_text), tools_dir, env)
        return

    elf = tools_dir / "sdk.elf"
    if shutil.which("host-client", path=env.get("PATH")) is None:
        generate_raw_app_bin(elf, tools_dir, tool_dir, chip)
        return

    script = tools_dir / "download.sh"
    if not script.is_file():
        raise BuildError(f"Jieli postbuild script not found: {script}")
    _run(["bash", str(script), "sdk"], tools_dir, env)

def find_qio_artifact(tools_dir: Path) -> Path:
    # Without the vendor host-client, app.bin is the artifact generated by the
    # current build. Prefer it over stale packages kept in the SDK checkout.
    for name in ("app.bin", "jl_isd.ufw", "jl_isd.fw"):
        candidate = tools_dir / name
        if candidate.is_file() and candidate.stat().st_size > 0:
            return candidate
    raise BuildError(
        f"Jieli postbuild produced no flash package in {tools_dir}; "
        "expected jl_isd.ufw, jl_isd.fw, or app.bin"
    )

def tuya_qio_name(params: Mapping[str, str]) -> str:
    project = params.get("CONFIG_PROJECT_NAME", "jieli_uart_hello")
    version = params.get("CONFIG_PROJECT_VERSION", "1.0.0")
    return f"{project}_QIO_{version}.bin"
